[programs.localnet]
crunchy_vs_smooth = "HbGs5BfZaxBgpwY41YH1KgvLtEgUaSeKBMT47ADeDyGM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/girri/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
